In [1]:
import pandas as pd
import datetime

In [2]:
air = pd.read_csv('/content/drive/MyDrive/DF/DF - 수소버스/2022년 일별평균대기오염도_2022.csv', encoding="cp949")
air.head()

,측정일시,측정소명,이산화질소농도(ppm),오존농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),미세먼지농도(㎍/㎥),초미세먼지농도(㎍/㎥)
0,20220101,강남구,0.029,0.014,0.5,0.003,25.0,12.0
1,20220101,홍릉로,0.038,0.009,0.6,0.004,27.0,16.0
2,20220101,행주,0.034,0.012,0.7,0.004,27.0,16.0
3,20220101,항동,0.030,0.011,0.5,0.003,27.0,14.0
4,20220101,한강대로,0.037,0.011,0.6,0.003,34.0,14.0

In [3]:
weather = pd.read_csv("/content/drive/MyDrive/DF/DF - 수소버스/일별기상.csv", encoding='cp949')
weather.head()

,day,Temp,rainfall,W_s,Humi,Dew,Press,rand_temp,See_1,W_d
0,2022-01-01,-4.595652,0.200671,0.916291,44.391304,-15.078261,1020.221739,-2.982609,1,NE
1,2022-01-02,-1.150000,0.139762,1.225000,58.875000,-8.450000,1015.654167,-0.891667,1,NE
2,2022-01-03,-2.387500,0.000000,1.063273,56.083333,-10.100000,1015.504167,-2.170833,1,W
3,2022-01-04,-1.970833,0.000000,1.215160,55.000000,-10.566667,1016.833333,-1.300000,1,WNW
4,2022-01-05,-3.066667,0.200671,1.002468,46.375000,-13.104167,1017.091667,-2.816667,1,NE

In [4]:
format = '%Y-%m-%d'
air['측정일시'] = air['측정일시'].apply(lambda x: pd.to_datetime(str(x), format= format))
weather['day'] = weather['day'].apply(lambda x: pd.to_datetime(str(x), format= format))

In [5]:
df = pd.merge(air, weather, left_on='측정일시', right_on='day')
df.drop(['day'],axis=1, inplace=True)
df.head()

,측정일시,측정소명,이산화질소농도(ppm),오존농도(ppm),일산화탄소농도(ppm),아황산가스농도(ppm),미세먼지농도(㎍/㎥),초미세먼지농도(㎍/㎥),Temp,rainfall,W_s,Humi,Dew,Press,rand_temp,See_1,W_d
0,2022-01-01,강남구,0.029,0.014,0.5,0.003,25.0,12.0,-4.595652,0.200671,0.916291,44.391304,-15.078261,1020.221739,-2.982609,1,NE
1,2022-01-01,홍릉로,0.038,0.009,0.6,0.004,27.0,16.0,-4.595652,0.200671,0.916291,44.391304,-15.078261,1020.221739,-2.982609,1,NE
2,2022-01-01,행주,0.034,0.012,0.7,0.004,27.0,16.0,-4.595652,0.200671,0.916291,44.391304,-15.078261,1020.221739,-2.982609,1,NE
3,2022-01-01,항동,0.030,0.011,0.5,0.003,27.0,14.0,-4.595652,0.200671,0.916291,44.391304,-15.078261,1020.221739,-2.982609,1,NE
4,2022-01-01,한강대로,0.037,0.011,0.6,0.003,34.0,14.0,-4.595652,0.200671,0.916291,44.391304,-15.078261,1020.221739,-2.982609,1,NE

In [6]:
df = df.fillna(df.median())
df.isnull().sum()

<ipython-input-6-fc04feaabb8e>:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df = df.fillna(df.median())
<ipython-input-6-fc04feaabb8e>:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.median())

측정일시            0
측정소명            0
이산화질소농도(ppm)    0
오존농도(ppm)       0
일산화탄소농도(ppm)    0
아황산가스농도(ppm)    0
미세먼지농도(㎍/㎥)     0
초미세먼지농도(㎍/㎥)    0
Temp            0
rainfall        0
W_s             0
Humi            0
Dew             0
Press           0
rand_temp       0
See_1           0
W_d             0
dtype: int64

In [7]:
#변수선택한 독립변수들만 추출
col = ['측정일시', '측정소명', 'W_s','Dew','Press','See_1', '일산화탄소농도(ppm)','미세먼지농도(㎍/㎥)', '초미세먼지농도(㎍/㎥)']
df = df[col]

In [8]:
def change_value(x):
  if x >= 18:
    return 1
  else:
    return 0

In [9]:
df.iloc[:,8] = df.iloc[:,8].apply(change_value)
df['초미세먼지농도(㎍/㎥)'].value_counts()

<ipython-input-9-c5eb9fbb8cb2>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.iloc[:,8] = df.iloc[:,8].apply(change_value)

0    10636
1     7614
Name: 초미세먼지농도(㎍/㎥), dtype: int64

# 모델링

In [10]:
#train, test 분리
from sklearn.model_selection import train_test_split
feature = df.iloc[:,:8]
target = df['초미세먼지농도(㎍/㎥)']

X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.3, stratify=target, random_state=100)

In [11]:
#oversampling
from imblearn.over_sampling import RandomOverSampler
X_train2, y_train2 = RandomOverSampler(random_state=0).fit_resample(X_train, y_train)
X_test2, y_test2 = RandomOverSampler(random_state=0).fit_resample(X_test, y_test)

In [12]:
X_test2

,측정일시,측정소명,W_s,Dew,Press,See_1,일산화탄소농도(ppm),미세먼지농도(㎍/㎥)
0,2022-08-22,중구,1.210203,22.250000,994.291667,1,0.4,22.0
1,2022-05-14,중랑구,1.432104,3.862500,1001.316667,1,0.3,31.0
2,2022-10-10,화랑로,1.511458,5.570833,1003.158333,1,0.3,9.0
3,2022-01-21,용산구,1.017643,-10.904167,1019.470833,1,0.6,37.0
4,2022-02-26,영등포구,1.567747,2.391667,1007.475000,0,0.5,64.0
...,...,...,...,...,...,...,...,...
6377,2022-05-11,은평구,1.218861,8.350000,1004.720833,1,0.3,39.0
6378,2022-02-18,정릉로,1.044391,-13.975000,1019.087500,1,0.7,45.0
6379,2022-02-15,동작대로,1.544899,-11.287500,1010.854167,1,0.5,36.0
6380,2022-01-02,동대문구,1.225000,-8.450000,1015.654167,1,0.5,37.0
6381,2022-03-03,광진구,1.146079,-4.033333,1007.166667,1,0.4,48.0

In [13]:
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt

In [14]:
# 종속변수가 이진 모델 (binomial) -> 로지스틱 모델 사용
from sklearn.linear_model import LogisticRegression

# 로지스틱 회귀 모델 생성 (L1 정규화 적용)
# max_iter 매개변수 설정하지 않으면 수렴 실패 -> max_iter 매개변수 늘리기
logit_model = LogisticRegression(penalty='l1', solver='liblinear', random_state=100, max_iter=1000)

# 모델 학습
logit_model.fit(X_train2.iloc[:,2:8], y_train2)

# 모델 예측
y_pred = logit_model.predict(X_test2.iloc[:,2:8])

In [15]:
# 모델 성능 평가
from sklearn.metrics import roc_auc_score, roc_curve, accuracy_score, precision_score, recall_score, f1_score

auc = roc_auc_score(y_test2, y_pred)
accuracy = accuracy_score(y_test2, y_pred)
recall = recall_score(y_test2, y_pred)
precision = precision_score(y_test2, y_pred)
f1 = f1_score(y_test2, y_pred)

print("AUC:", auc)
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("F1 스코어:", f1)

AUC: 0.8672829833907866
Accuracy: 0.8672829833907866
Recall: 0.8523973675963648
Precision: 0.8785529715762274
F1 스코어: 0.8652775568633688

In [16]:
X_test2['pred'] = y_pred
result = X_test2['측정소명'].loc[X_test2['pred']==1].value_counts().to_frame()
result.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 동작대로 to 북한산
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   측정소명    50 non-null     int64
dtypes: int64(1)
memory usage: 800.0+ bytes

In [17]:
#!apt-get update -qq
#!apt-get install fonts-nanum* -qq

In [ ]:
import matplotlib.font_manager as fm

fonts = fm.findSystemFonts(fontpaths=None, fontext='ttf')
for font in fonts:
    if 'Nanum' in font or 'Malgun' in font:  # 나눔글꼴 또는 맑은고딕 폰트 확인
        print(font)

In [29]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'Malgun Gothic'
matplotlib.rcParams['font.size'] = 15 # 글자 크기
matplotlib.rcParams['axes.unicode_minus'] = False

In [ ]:
idx = result.index
plt.bar(idx, result['측정소명'])
plt.show()

In [32]:
result.to_csv("/content/drive/MyDrive/DF/DF - 수소버스/result_glm.scv")